import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
      absolute: "Absolute title", //? Use for those pages where the title is not specified, or we can use the same object in the pages and give the absolute title
      default: "Fallback", //? Fallback title in absence of absolute title or page title
      template: "%s | With template", //? Use as a template for the all titles (%s is replaced with the page title)
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`p-4 min-h-screen flex ${inter.className}`}>
      <main>{children}</main>
      <footer className="mt-auto">Main footer</footer>
      </body>
    </html>
  );
}
